export const US_STATES = [
  "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", 
  "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", 
  "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", 
  "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", 
  "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", 
  "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", 
  "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", 
  "Wisconsin", "Wyoming"
];

export const CAPITALS = [
  "Montgomery", "Juneau", "Phoenix", "Little Rock", "Sacramento", "Denver", "Hartford", 
  "Dover", "Tallahassee", "Atlanta", "Honolulu", "Boise", "Springfield", "Indianapolis", 
  "Des Moines", "Topeka", "Frankfort", "Baton Rouge", "Augusta", "Annapolis", "Boston", 
  "Lansing", "St. Paul", "Jackson", "Jefferson City", "Helena", "Lincoln", "Carson City", 
  "Concord", "Trenton", "Santa Fe", "Albany", "Raleigh", "Bismarck", "Columbus", 
  "Oklahoma City", "Salem", "Harrisburg", "Providence", "Columbia", "Pierre", 
  "Nashville", "Austin", "Salt Lake City", "Montpelier", "Richmond", "Olympia", 
  "Charleston", "Madison", "Cheyenne"
];

export const PRONUNCIATION_ALIASES = {
  // --- STATES ---
  "our kansas": "Arkansas",
  "arkansaw": "Arkansas",
  "at the hole": "Idaho",
  "illinoise": "Illinois",
  "ill a noy": "Illinois",
  "connect a cut": "Connecticut",
  "ken net i cut": "Connecticut",
  "mary land": "Maryland",
  "mare a land": "Maryland",
  "mass chew sets": "Massachusetts",
  "massa chew sets": "Massachusetts",
  "organ": "Oregon", 
  "or e gone": "Oregon",
  "aura gone": "Oregon",
  "lou easy anna": "Louisiana",
  "louise e anna": "Louisiana",
  "ha why ee": "Hawaii",
  "ha why": "Hawaii",
  "how why ee": "Hawaii",
  "call a raw dough": "Colorado",
  "color ah dough": "Colorado",
  "na va da": "Nevada",
  "why oh ming": "Wyoming",
  "ten a see": "Tennessee",
  "miss is hippy": "Mississippi",
  "main": "Maine",
  "mane": "Maine",
  "men": "Maine", 
  "man": "Maine", 
  "lowa": "Iowa", 
  "eye oh wa": "Iowa",
  "eye a wa": "Iowa",
  "misery": "Missouri", 
  "miz er ee": "Missouri",
  "muh zur ee": "Missouri",
  "nuh brass ka": "Nebraska",
  "new brass ka": "Nebraska",
  "ne brass ka": "Nebraska",
  "deli wear": "Delaware",
  "della wear": "Delaware",
  "deli where": "Delaware",
  "della where": "Delaware",
  "dela wear": "Delaware",

  // --- CAPITALS ---
  "de moyn": "Des Moines",
  "da moyn": "Des Moines",
  "day moyn": "Des Moines",
  "des, moines": "Des Moines",
  "des,moines": "Des Moines",
  "dez moynes": "Des Moines",
  "des moynes": "Des Moines",
  "they moist": "Des Moines", 
  "the moist": "Des Moines",  
  "peer": "Pierre",
  "pier": "Pierre",
  "pee air": "Pierre",
  "bat and rouge": "Baton Rouge",
  "bat in rouge": "Baton Rouge",
  "batton rouge": "Baton Rouge",
  "better watch": "Baton Rouge", 
  "mont pill ear": "Montpelier",
  "mont peel yer": "Montpelier",
  "mont pelly er": "Montpelier",
  "helen uh": "Helena",
  "hell in a": "Helena",
  "to peak uh": "Topeka",
  "two peak uh": "Topeka",
  "toe peak ah": "Topeka",
  "topica": "Topeka",
  "toe pika": "Topeka",
  "boy zee": "Boise",
  "boys e": "Boise",
  "boy see": "Boise",
  "boy z": "Boise",
  "noise e": "Boise",
  "shy ann": "Cheyenne",
  "shy anne": "Cheyenne",
  "shy an": "Cheyenne",
  "shine": "Cheyenne",
  "conquered": "Concord", 
  "con cord": "Concord",
  "frank ford": "Frankfort", 
  "frank fort": "Frankfort",
  "frank furd": "Frankfort",
  "ha na loo loo": "Honolulu",
  "hana lulu": "Honolulu",
  "honda lulu": "Honolulu", 
  "jew no": "Juneau",
  "juno": "Juneau",
  "fee nix": "Phoenix",
  "feenix": "Phoenix",
  "raw lee": "Raleigh",
  "rah lee": "Raleigh",
  "rolly": "Raleigh",
  "rally": "Raleigh", 
  "really": "Raleigh", 
  "riley": "Raleigh",
  "rawly": "Raleigh",
  "sack ra men toe": "Sacramento",
  "sacra mento": "Sacramento",
  "talla has see": "Tallahassee",
  "tall a has see": "Tallahassee",
  "telly has see": "Tallahassee",
  "tell a has see": "Tallahassee",
  "tally has see": "Tallahassee",
  "tall a hassey": "Tallahassee",
  "biz mark": "Bismarck",
  "bismark": "Bismarck",
  "mad a sun": "Madison",
  "mad is in": "Madison",
  "uh gus ta": "Augusta",
  "ah gus ta": "Augusta",
  "a gus ta": "Augusta",
  "hair is burg": "Harrisburg",
  "harris burg": "Harrisburg",
  "heart ford": "Hartford",
  "hard ford": "Hartford",
  "heart furd": "Hartford",
  "harvard": "Hartford", 
  "chanton": "Trenton", 
  "canton": "Trenton",
  "trent in": "Trenton",
  "tren ton": "Trenton",
  "an apple is": "Annapolis", 
  "uh napolis": "Annapolis",
  "ah napolis": "Annapolis",
  "and apple is": "Annapolis",
  "in napolis": "Annapolis",
  "sail um": "Salem",
  "say lum": "Salem",
  "sail em": "Salem",
  "indiana police": "Indianapolis",
  "indiana please": "Indianapolis",
  "in the annapolis": "Indianapolis",
  "indian apple is": "Indianapolis",
  "indiana polis": "Indianapolis",
  "over": "Dover" 
};

export const RECOGNITION_LIST = [...US_STATES, ...CAPITALS];